DROP DATABASE Mydb;
CREATE DATABASE Mydb;
USE Mydb;
CREATE TABLE users(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  login VARCHAR(25) NOT NULL UNIQUE
);
CREATE TABLE groups(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(25) NOT NULL UNIQUE
);
CREATE TABLE users_groups(
  user_id INT NOT NULL  ,
  group_id INT NOT NULL,
  PRIMARY KEY (user_id, group_id),
  FOREIGN KEY (user_id) REFERENCES users(id)
  ON DELETE CASCADE,
  FOREIGN KEY (group_id) REFERENCES groups(id)
  ON DELETE CASCADE
);
